name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2.4.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY }}'
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: '${{ steps.login-ecr.outputs.registry }}'
          ECR_REPOSITORY: "valuation_pipeline"
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -f ./projects/valuation_pipeline/Dockerfile . \
          --build-arg DATA_HOST='${{ secrets.DATA_HOST }}' \
          --build-arg DATA_USER='${{ secrets.DATA_USER }}' \
          --build-arg DATA_PASSWORD='${{ secrets.DATA_PASSWORD }}' \
          --build-arg AWS_ACCESS_KEY='${{ secrets.AWS_ACCESS_KEY }}' \
          --build-arg AWS_SECRET_KEY='${{ secrets.AWS_SECRET_KEY }}' \
          --build-arg AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
          --build-arg AWS_ACCOUNT_ID='${{ secrets.AWS_ACCOUNT_ID }}' \
          --build-arg AWS_RDS_PASSWORD='${{ secrets.AWS_RDS_PASSWORD }}' \
          --build-arg AWS_RDS_USER='${{ secrets.AWS_RDS_USER }}' \
          --build-arg AWS_RDS_HOST='${{ secrets.AWS_RDS_HOST }}'
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: '${{ steps.login-ecr.outputs.registry }}'
          ECR_REPOSITORY: "valuation_frontend"
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -f ./projects/valuation_frontend/Dockerfile . \
          --build-arg AWS_ACCESS_KEY='${{ secrets.AWS_ACCESS_KEY }}' \
          --build-arg AWS_SECRET_KEY='${{ secrets.AWS_SECRET_KEY }}' \
          --build-arg AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
          --build-arg AWS_ACCOUNT_ID='${{ secrets.AWS_ACCOUNT_ID }}' \
          --build-arg AWS_RDS_PASSWORD='${{ secrets.AWS_RDS_PASSWORD }}' \
          --build-arg AWS_RDS_USER='${{ secrets.AWS_RDS_USER }}' \
          --build-arg AWS_RDS_HOST='${{ secrets.AWS_RDS_HOST }}'
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
